export let student_info = [
    {
        "id": "1",
        "student_name": "RDM",
        "student_id": "421160864",
        "current_year": "3",
        "year_of_entarance": "2021",
        "course": "Bsc in IT",
        "current_gpa":"2.78",
    },
    {
        "id": "2",
        "student_name": "RDM",
        "student_id": "421160864",
        "current_year": "3",
        "year_of_entarance": "2021",
        "course": "Bsc in IT",
        "current_gpa":"2.78",
    },
    {
        "id": "3",
        "student_name": "RDM",
        "student_id": "421160864",
        "current_year": "3",
        "year_of_entarance": "2021",
        "course": "Bsc in IT",
        "current_gpa":"2.78",
    },
    {
        "id": "4",
        "student_name": "RDM",
        "student_id": "421160864",
        "current_year": "3",
        "year_of_entarance": "2021",
        "course": "Bsc in IT",
        "current_gpa":"2.78",
    },
    {
        "id": "5",
        "student_name": "RDM",
        "student_id": "421160864",
        "current_year": "3",
        "year_of_entarance": "2021",
        "course": "Bsc in IT",
        "current_gpa":"2.78",
    },
    {
        "id": "6",
        "student_name": "RDM",
        "student_id": "421160864",
        "current_year": "3",
        "year_of_entarance": "2021",
        "course": "Bsc in IT",
        "current_gpa":"2.78",
    },
]

// export let student_info = {
//             id: "1",
//             student_name: "RDM",
//             student_id: "421160864",
//             current_year: "3",
//             year_of_entarance: "2021",
//             course: "Bsc in IT",
//             current_gpa:"2.78",
//         }